/* Text-node translations for the custom FordPass CRM case layout. */
window.FORD_CASE_PT = {
  "Client": "Cliente",
  "Role": "Função",
  "Year": "Ano",
  "Scope": "Escopo",
  "Ford Motor Company · Brazil": "Ford Motor Company · Brasil",
  "Product Designer · End to end": "Designer de produto · Ponta a ponta",
  "Strategy · CRM · UX writing · Push": "Estratégia · CRM · UX Writing · Notificações",
  "Driving connected": "Impulsionando a ativação",
  "vehicle": "de veículos",
  "activation": "conectados",
  "in Brazil.": "no Brasil.",
  "Two CRM journeys, a push cadence and in-app UX writing, built from scratch to move Ford owners from app download to full modem activation.": "Duas jornadas de CRM, uma cadência de notificações e textos no app, criados do zero para levar proprietários da Ford do download à ativação completa do modem.",
  "The features were already there. What was missing was anyone telling owners how to turn them on.": "Os recursos já existiam. Faltava mostrar aos proprietários como ativá-los.",
  "The full case is an interactive Figma prototype.": "O estudo completo está em um protótipo interativo no Figma.",
  "All screens, transitions and email flows.": "Todas as telas, transições e jornadas de e-mail.",
  "The prototype is the best way to review this one.": "O protótipo é a melhor maneira de explorar este projeto.",
  "Every screen, email and flow is in Figma.": "Todas as telas, mensagens e etapas estão no Figma.",
  "Open prototype": "Abrir protótipo",
  "A significant portion of Brazilian owners": "Uma parcela significativa dos proprietários brasileiros",
  "weren't activating connected services, and no CRM communication existed to guide them.": "não ativava os serviços conectados, e não havia comunicação de CRM para orientá-los.",
  "Starting point": "Ponto de partida",
  "Signals": "Sinais",
  "Why activation was failing": "Por que a ativação falhava",
  "Internal observations, CRM performance and support patterns all pointed at the same gap.": "Observações internas, desempenho do CRM e padrões de atendimento apontavam para a mesma lacuna.",
  "Many users downloaded the app but never activated connected services.": "Muitos usuários baixavam o app, mas nunca ativavam os serviços conectados.",
  "Dealerships were being used as a crutch to complete basic activation steps.": "As concessionárias acabavam ajudando a concluir etapas básicas de ativação.",
  "No dedicated CRM journey existed": "Não existia uma jornada de CRM dedicada",
  "for connected vehicle activation.": "à ativação de veículos conectados.",
  "Users with less digital familiarity dropped off more often.": "Pessoas menos familiarizadas com o digital desistiam com mais frequência.",
  "Pre-2019 vehicles support basic services only; 2019+ vehicles need modem activation. No communication explained the difference.": "Veículos anteriores a 2019 oferecem apenas serviços básicos; os de 2019 em diante exigem a ativação do modem. Nenhuma comunicação explicava essa diferença.",
  "Diagnosis": "Diagnóstico",
  "There was no journey to fix, so we built one": "Não havia uma jornada para corrigir. Então criamos uma.",
  "Without a structured CRM journey, communications were generic and not tied to what each vehicle could do. No channel guided owners from awareness to modem activation, and many connected-vehicle owners didn't know what they could unlock.": "Sem uma jornada estruturada de CRM, as mensagens eram genéricas e não consideravam os recursos de cada veículo. Nenhum canal conduzia os proprietários da descoberta à ativação do modem, e muitos nem sabiam o que poderiam habilitar.",
  "So the job was to build a dedicated communication strategy from the ground up.": "Por isso, o trabalho era construir do zero uma estratégia de comunicação dedicada.",
  "Research": "Pesquisa",
  "Audience": "Público",
  "Ford Nation is Ford's most engaged owner community, the first to get product updates and invitations to events. If": "Ford Nation é a comunidade de proprietários mais engajada da Ford, a primeira a receber novidades e convites para eventos. Se",
  "they": "eles",
  "were struggling with activation, most owners were too.": "tinham dificuldade para ativar os serviços, provavelmente os demais proprietários também tinham.",
  "Online survey · 142 respondents · 2 weeks · May 2024": "Pesquisa online · 142 respondentes · 2 semanas · maio de 2024",
  "Survey findings": "Resultados da pesquisa",
  "Ford App installed": "App da Ford instalado",
  "have the app installed, but 11% had uninstalled it after downloading.": "tinham o app instalado, mas 11% o desinstalaram após o download.",
  "Never received comms": "Nunca receberam mensagens",
  "had never received any communication from Ford about connected services.": "nunca haviam recebido uma comunicação da Ford sobre serviços conectados.",
  "Didn't activate anything": "Não ativaram nenhum recurso",
  "did not activate any available service, and another 17% didn't know the services existed.": "não ativaram nenhum serviço disponível, e outros 17% nem sabiam que eles existiam.",
  "Biggest difficulty": "Maior dificuldade",
  "said \"I didn't understand which services applied to my car.\"": "disseram: \"Não entendi quais serviços estavam disponíveis para o meu carro.\"",
  "Instructions clarity": "Clareza das instruções",
  "rated in-app instructions as": "consideraram as instruções no app",
  "somewhat unclear": "pouco claras",
  "or": "ou",
  "confusing": "confusas",
  "Needed help to activate": "Precisaram de ajuda para ativar",
  "went to a dealership or contacted support to complete activation.": "recorreram a uma concessionária ou ao suporte para concluir a ativação.",
  "Activation should walk people through one step at a time.": "A ativação deve orientar as pessoas uma etapa de cada vez.",
  "A checklist leaves them on their own.": "Uma lista de tarefas as deixa por conta própria.",
  "Insight from desk research": "Aprendizado da pesquisa exploratória",
  "Hypotheses": "Hipóteses",
  "Three directions": "Três caminhos",
  "A CSD matrix produced three directions. I tested each against the root problem, that nobody was reaching users after download, and only one addressed it.": "Uma matriz de Certezas, Suposições e Dúvidas trouxe três caminhos. Comparei cada um ao problema central — ninguém falava com os usuários depois do download — e apenas um o resolvia.",
  "H1 · Rejected": "H1 · Descartada",
  "Clearer in-app guidance": "Orientações mais claras no app",
  "It would help people who reach the activation screen, but most never got that far.": "Ajudaria quem chegasse à tela de ativação, mas a maioria nem alcançava esse ponto.",
  "H2 · Rejected": "H2 · Descartada",
  "Redesigning the website": "Redesenhar o site",
  "Good for awareness, but it wouldn't reach people who had already downloaded the app and stalled. Wrong channel for that stage of the funnel.": "Bom para apresentar os serviços, mas não alcançaria quem já havia baixado o app e parado. Era o canal errado para essa etapa da jornada.",
  "H3 · Selected": "H3 · Escolhida",
  "A dedicated CRM and push strategy": "Uma estratégia dedicada de CRM e notificações",
  "Reaches people after download, where they were getting lost, and ties CRM, push and in-app copy into one activation journey.": "Alcança as pessoas depois do download, onde elas se perdiam, e une CRM, notificações e textos no app em uma jornada de ativação.",
  "Solution": "Solução",
  "Core idea": "Ideia central",
  "Make the Ford App the place where activation happens, with clear UX writing and guidance for each vehicle": "Fazer do app da Ford o lugar da ativação, com textos claros e orientações para cada veículo",
  "Four pieces of work came out of it, all under one system:": "A solução reuniu quatro frentes em um só sistema:",
  "\"Minhas Experiências Ford\"": "\"Minhas Experiências Ford\"",
  ": a CRM journey for account activation and first use.": ": uma jornada de CRM para ativar a conta e orientar o primeiro uso.",
  "Modem Activation": "Ativação do modem",
  ": a dedicated CRM journey for 2019+ vehicles.": ": uma jornada de CRM dedicada a veículos de 2019 em diante.",
  "Push notification cadence": "Cadência de notificações",
  ": triggers on day 3, 7, 15 and 30 for users stuck in the funnel.": ": disparos nos dias 3, 7, 15 e 30 para quem ficou parado na jornada.",
  "In-app UX writing": "Textos no app",
  ": the same terms as the CRM and push messages, so users always know where they are.": ": os mesmos termos usados no CRM e nas notificações, para que as pessoas saibam sempre em que etapa estão.",
  "Principle 1": "Princípio 1",
  "Activation by vehicle": "Ativação por veículo",
  "Flows follow the vehicle's generation: pre-2019 owners are guided to basic services, 2019+ owners to modem activation.": "Os fluxos seguem a geração do veículo: proprietários de modelos anteriores a 2019 são orientados aos serviços básicos; os demais, à ativação do modem.",
  "Principle 2": "Princípio 2",
  "One vocabulary": "Um só vocabulário",
  "CRM, push and in-app use the same terminology, so owners can tell where they are and what comes next.": "CRM, notificações e app usam os mesmos termos para que os proprietários saibam onde estão e qual é o próximo passo.",
  "Principle 3": "Princípio 3",
  "Help at every step": "Ajuda em cada etapa",
  "FORDi, Guia 360 and dealership support are linked from inside the communication flow, so no message is a dead end.": "FORDi, Guia 360 e suporte da concessionária estão acessíveis na própria comunicação; nenhuma mensagem termina sem um próximo caminho.",
  "Activation flow for a 2019+ connected vehicle": "Fluxo de ativação de um veículo conectado a partir de 2019",
  "Step 1": "Etapa 1",
  "Owner buys a connected vehicle (2019+).": "Proprietário compra um veículo conectado (2019+).",
  "CRM trigger": "Disparo de CRM",
  ": 3 emails guiding account creation.": ": 3 e-mails orientam a criação da conta.",
  "Step 2": "Etapa 2",
  "App download, account registration, chassis activation.": "Download do app, criação da conta e ativação do chassi.",
  "CRM + push": "CRM + notificações",
  "Modem Activation journey (3 emails) plus push on day 3, 7, 15 and 30.": "Jornada de ativação do modem (3 e-mails) e notificações nos dias 3, 7, 15 e 30.",
  "Step 3": "Etapa 3",
  "Modem activated; all connected services unlocked.": "Modem ativado; todos os serviços conectados disponíveis.",
  "Results": "Resultados",
  "Impact": "Impacto",
  "After rollout, every tracked metric moved in the right direction. Full modem activation, the project's main goal, went from 11.3% to 16.5%.": "Depois do lançamento, todos os indicadores acompanhados avançaram. A ativação completa do modem, principal objetivo do projeto, passou de 11,3% para 16,5%.",
  "Key product metrics, before and after rollout": "Principais indicadores do produto, antes e depois do lançamento",
  "Metric": "Indicador",
  "Before": "Antes",
  "After": "Depois",
  "Change": "Variação",
  "Account & registration": "Conta e cadastro",
  "Total registered accounts": "Total de contas cadastradas",
  "Accounts with chassis registered, pre-2019": "Contas com chassi cadastrado, antes de 2019",
  "Accounts with chassis registered, 2019+": "Contas com chassi cadastrado, 2019+",
  "Activation funnel, 2019+": "Jornada de ativação, 2019+",
  "Users with account but no chassis": "Usuários com conta, sem chassi",
  "Chassis activated, no modem": "Chassi ativado, sem modem",
  "Full activation (chassis + modem)": "Ativação completa (chassi + modem)",
  "Support & drop-off": "Suporte e desistência",
  "Activation-related support requests / month": "Chamados de suporte sobre ativação / mês",
  "Drop-off rate during activation flow": "Taxa de desistência durante a ativação",
  "Users requiring dealership assistance": "Usuários que precisaram da concessionária",
  "Engagement": "Engajamento",
  "App return rate within 30 days of activation": "Retorno ao app em até 30 dias após ativação",
  "Connected services usage after activation": "Uso de serviços conectados após ativação",
  "Constraints": "Restrições",
  "What limited the work": "O que limitou o trabalho",
  "Four things got in the way. Next time I'd plan around them from the start.": "Quatro fatores atrapalharam o projeto. Da próxima vez, eu os consideraria desde o início.",
  "App ownership": "Gestão do app",
  "Limited control over the app itself": "Controle limitado sobre o aplicativo",
  "The Ford App is managed globally. Our scope was the communication layer (in-app messages and push), not the product surface, so we could influence it but not own it.": "O app da Ford é gerido globalmente. Nosso escopo era a camada de comunicação — mensagens no app e notificações —, não a interface do produto. Podíamos influenciá-la, mas não controlá-la.",
  "Data": "Dados",
  "Activation data latency": "Atraso nos dados de ativação",
  "Lists of non-activated users arrived on a schedule, not in real time. Someone who activated on Tuesday could still get a push on Wednesday.": "As listas de usuários sem ativação chegavam periodicamente, não em tempo real. Alguém que ativasse na terça ainda poderia receber uma notificação na quarta.",
  "Email": "E-mail",
  "Email layout constraints": "Limites do layout de e-mail",
  "The CRM team works with modular templates. I owned the UX writing and content strategy; the visual layout had to fit existing modules.": "A equipe de CRM usa templates modulares. Eu era responsável pelos textos de UX e pela estratégia de conteúdo; o layout visual precisava caber nos módulos existentes.",
  "Attribution": "Atribuição",
  "Measuring indirect impact": "Medir o impacto indireto",
  "Several initiatives ran in parallel, which makes it hard to isolate the": "Várias iniciativas aconteceram em paralelo, dificultando isolar a contribuição",
  "exact": "exata",
  "contribution of each CRM journey or push to modem activation.": "de cada jornada de CRM ou notificação para a ativação do modem.",
  "Reflection": "Reflexão",
  "To get someone to activate a service,": "Para levar alguém a ativar um serviço,",
  "reach them at the right moment with one clear next step.": "é preciso encontrá-lo no momento certo e mostrar um próximo passo claro.",
  "Takeaways": "Aprendizados",
  "Nobody briefed a CRM journey. The diagnosis showed it was the missing piece.": "Ninguém havia pedido uma jornada de CRM. O diagnóstico mostrou que ela era a peça que faltava.",
  "People stalled because they weren't sure what applied to their car, more than because the steps were hard.": "As pessoas paravam mais por não saber quais serviços serviam para seu carro do que pela dificuldade das etapas.",
  "We couldn't change the app, so we worked in the channels we did control: email, push and in-app copy.": "Não podíamos mudar o app, então trabalhamos nos canais sob nosso controle: e-mail, notificações e textos dentro do aplicativo.",
  "Most of the useful work happened before any screen was designed: the survey, the diagnosis and choosing between three hypotheses.": "Grande parte do trabalho valioso aconteceu antes de desenhar qualquer tela: a pesquisa, o diagnóstico e a escolha entre três hipóteses.",
};
